version: '3'

services:
  unifi-protect:
    image: thepagan/unifi-protect-arm64:2.2.6
    container_name: unifi-protect
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /storage/srv:/srv
      - /storage/data:/data
      - /storage/persistent:/persistent
    environment:
      - STORAGE_DISK=/dev/sda1
    restart: unless-stopped
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    privileged: true
    network_mode: host
